version: "3.1"
services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: collinsongroup/dashboard_api:latest
    depends_on:
      - elastic_config
      - elastic_data    
    secrets:
      - dashboard_public_key
    environment:
      NO_JWT: "true"
      ES_CONFIG_HOST: elastic_config:9200
      ES_DATA_HOST: elastic_data:9200
  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    image: collinsongroup/dashboard:latest
    depends_on:
      - api
  elastic_data:
    build: 
      context: ../db
      dockerfile: Dockerfile
    image: collinsongroup/elasticsearch:latest
  elastic_config:
    build: 
      context: ../db
      dockerfile: Dockerfile
    image: collinsongroup/elasticsearch:latest
  kibana:
    build:
      context: ../kibana
      dockerfile: Dockerfile
    image: collinsongroup/kibana:latest
    depends_on:
      - elastic_data
    environment:
      ELASTICSEARCH_URL: http://elastic_data:9200
    ports:
     - "5601:5601"
  uptime_prospector:
    build:
      context: ../uptime_prospector
      dockerfile: Dockerfile
    image: collinsongroup/uptime_prospector:latest
    depends_on:
      - elastic_config
      - elastic_data
    restart: always
    deploy:
      restart_policy:
        condition: any        
    environment:
      ES_CONFIG_HOST: elastic_config:9200
      ES_DATA_HOST: elastic_data:9200
      SITE_CONFIG: ./config/flightdata.json
      MIN_FINISH_TIME: 30000
    secrets:
      - dashboard_private_key
      - dashboard_passphrase
  webserver:
    build:
      context: ../webserver
      dockerfile: Dockerfile
    image: collinsongroup/dashboard_server:latest
    depends_on: 
      - api
      - dashboard
      - kibana
    ports: 
      - "80:80"
secrets:
  dashboard_private_key:
    external: true
  dashboard_public_key:
    external: true
  dashboard_passphrase:
    external: true
    
  
