version: "3.1"
services:
  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    image: collinsongroup/dashboard:latest
  elastic:
    build: 
      context: ../db
      dockerfile: Dockerfile
    image: collinsongroup/elasticsearch:latest
  kibana:
    build:
      context: ../kibana
      dockerfile: Dockerfile
    image: collinsongroup/kibana:latest
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
     - "5601:5601"
  uptime_prospector:
    build:
      context: ../uptime_prospector
      dockerfile: Dockerfile
    image: collinsongroup/uptime_prospector:latest
    restart: always
    deploy:
      restart_policy:
        condition: any        
    environment:
      ES_HOST: elastic:9200
      SITE_CONFIG: ./config/flightdata.json
      MIN_FINISH_TIME: 30000
    secrets:
      - dashboard_private_key
      - dashboard_passphrase
  webserver:
    build:
      context: ../webserver
      dockerfile: Dockerfile
    image: collinsongroup/dashboard_server:latest
    ports: 
      - "80:80"
secrets:
  dashboard_private_key:
    external: true
  dashboard_public_key:
    external: true
  dashboard_passphrase:
    external: true
    
  
