version: "3"
services:
  elastic:
    build: 
      context: ../db
      dockerfile: Dockerfile
    image: collinsongroup/elasticsearch:latest
    ports:
     - "9200:9200"
  kibana:
    build:
      context: ../kibana
      dockerfile: Dockerfile
    image: collinsongroup/kibana:latest
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
     - "5601:5601"
  
